### ISSUE TITLE
Which generation of Optane are your test results based on?

### ISSUE THREAD

**Issue by UntaggedRui** [SJTU-IPADS/librdpma#1]
Is the optane you use first or second generation? [Intel® Optane™ Persistent Memory 128GB Module](https://www.intel.com/content/www/us/en/products/sku/190348/intel-optane-persistent-memory-128gb-module/specifications.html) or [Intel® Optane™ Persistent Memory 200 Series (128GB PMEM) Module](https://www.intel.com/content/www/us/en/products/sku/203879/intel-optane-persistent-memory-200-series-128gb-pmem-module/specifications.html)？

**Comment by wxdwfc** [comment]
We use the first generation.
