### ISSUE TITLE
question about additional read bandwidth

### ISSUE THREAD

**Issue by xywoo-cs** [SJTU-IPADS/librdpma#3]
Hi! This is a great work!   

But I'm having some problems in running one-sided benchs.  

`$ sudo numactl --cpubind=0 ./scripts/nvm_server --nvm_file /dev/dax0.0`
`$ sudo numactl --cpubind=0 ./scripts/nvm_client --payload=256 --threads=1 --coros=1 --use_read=true --random=true`

I have the client constantly sending one-sided reads to remote persistent memory, and use `pmwatch` to monitor bandwidth. I found some additional read requests to memory controlle rs. For random 256B reads, those extra reads cost about 0.25x the application-level bandwidth.  
It looks like the reason is prefetching from RNIC.

I think these extra read requests are not designed by `librdpma`, but by `libibverbs`. is there any way to avoid this extra reads?

Many thanks!

**Comment by wxdwfc** [comment]
Thanks for you interests! I think it is probably due to the read address unaligned. 

Adding:

`--round_up=true --round_payload=256` 

to the benchmark client (`nvm_client`) may address the issue.

**Comment by xywoo-cs** [comment]
Thanks, you're right, I'm an idiot
love this work👍
